### ISSUE TITLE
Twitter does not allow duplicate posts within a short time frame

### ISSUE THREAD

**Issue by m00dawg** [LightsOnHudson/FPP-Plugin-Tweeter#1]
Twitter does not allow duplicate posts within a short time frame, which means it may refuse to post a tweet if the same song comes up before the time expires. To get around this, adding a date to "Now Playing" should keep the tweets unique enough:

Here is what I did in functions.inc.php:

                        $message = "Now Playing at ".date('M jS, g:ia',time()).": ".$messageToSend;

**Comment by LightsOnHudson** [comment]
Funny, I did that last year, guess i never checked in the code for that! Thanks for this. I'll make the change and commit it this time!

Ben

**Comment by m00dawg** [comment]
:+1: :tada:

**Comment by LightsOnHudson** [comment]
Ok. I've changed this.. however; you will not be able to update the plugin unless you remove your changes and then hit the Update plugin button. you will know that the update took place because you should see V 1.0 in the plugin main screen.
Thanks for your help!

Ben

**Comment by m00dawg** [comment]
Looks like doing a 'git stash && git pull' in the plugin directory did the trick? Unless there is something else the Update plugin button is doing?

**Comment by LightsOnHudson** [comment]
I dont know how the workings of GIT really work and all the command line. I just delete the plugin, and re-install it. as the plugin SHOULD self update.. 

However; the update plugin runs a script in the /opt/fpp/scripts/update_plugin that Captain put in there.

**Comment by m00dawg** [comment]
Ah cool thanks for pointing that file out. Yup looks like that script is mostly doing a git pull and other stuff. As long as my git is clean it should work (if it wasn't the git pull would have failed, yup). I'll go ahead and carry those steps out via the GUI though just for completeness. Thanks for the fix!
